### ISSUE TITLE
关于是否进行增量预训练问题

### ISSUE THREAD

**Issue by Eren139** [ZixinxinWang/Legal-Eagle-InternLM#4]
你好！通过你对项目的描述我好像发现你没有进行法律领域的增量预训练，是intermlm本身就有法律领域的预训练知识吗？没有进行法律领域的增量预训练就直接微调的话效果怎么样呢？

**Comment by ZixinxinWang** [comment]
效果上还是会有幻觉的，这个不可避免。可以尝试进行增量预训练。在LLM预训练阶段，法律领域的知识肯定是训练过的。
https://github.com/hiyouga/LLaMA-Factory

**Comment by Eren139** [comment]
好的，十分感谢你的回答

> 效果上还是会有幻觉的，这个不可避免。可以尝试进行增量预训练。在LLM预训练阶段，法律领域的知识肯定是训练过的。 https://github.com/hiyouga/LLaMA-Factory
